version: 2
updates:
  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'saturday'
    reviewers:
      - 'kunalnagar'
    commit-message:
      prefix: 'chore'
      include: 'scope'
    open-pull-requests-limit: 10
    rebase-strategy: 'disabled'
