version: 2
updates:
- package-ecosystem: docker
  directory: "/ruby-node/2.7/buster/slim"
  schedule:
    interval: daily
  commit-message:
		prefix: chore
		include: scope
	open-pull-requests-limit: 10
	rebase-strategy: disabled
- package-ecosystem: docker
  directory: "/ruby-node/2.6/buster/slim"
  schedule:
    interval: daily
  commit-message:
		prefix: chore
		include: scope
	open-pull-requests-limit: 10
	rebase-strategy: disabled
- package-ecosystem: docker
  directory: "/ruby-node/2.7/buster"
  schedule:
    interval: daily
  commit-message:
		prefix: chore
		include: scope
	open-pull-requests-limit: 10
	rebase-strategy: disabled
- package-ecosystem: docker
  directory: "/ruby-node/2.6/buster"
  schedule:
    interval: daily
  commit-message:
		prefix: chore
		include: scope
	open-pull-requests-limit: 10
	rebase-strategy: disabled
- package-ecosystem: docker
  directory: "/ruby-node/2.7/alpine"
  schedule:
    interval: daily
  commit-message:
		prefix: chore
		include: scope
	open-pull-requests-limit: 10
	rebase-strategy: disabled
- package-ecosystem: docker
  directory: "/ruby-node/2.6/alpine"
  schedule:
    interval: daily
  commit-message:
		prefix: chore
		include: scope
	open-pull-requests-limit: 10
	rebase-strategy: disabled
