name: Lint Dockerfiles

on: [push, pull_request]

jobs:
  lint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: brew install hadolint
      - run: hadolint ruby-node/{2.6,2.7}/**/*Dockerfile
