name: Test Docker image

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: |
          echo "Running ==> 2.6"
          docker run -i $(docker build -q ruby-node/2.6/buster) /bin/sh -c "ruby --version && node --version && npm --version"
          echo "Running ==> 2.6 slim"
          docker run -i $(docker build -q ruby-node/2.6/buster/slim) /bin/sh -c "ruby --version && node --version && npm --version"
          echo "Running ==> 2.6 alpine"
          docker run -i $(docker build -q ruby-node/2.6/alpine) /bin/sh -c "ruby --version && node --version && npm --version"
          echo "Running ==> 2.7"
          docker run -i $(docker build -q ruby-node/2.7/buster) /bin/sh -c "ruby --version && node --version && npm --version"
          echo "Running ==> 2.7 slim"
          docker run -i $(docker build -q ruby-node/2.7/buster/slim) /bin/sh -c "ruby --version && node --version && npm --version"
          echo "Running ==> 2.7 alpine"
          docker run -i $(docker build -q ruby-node/2.7/alpine) /bin/sh -c "ruby --version && node --version && npm --version"
