name: ruby-node--lint

on: push

jobs:
  hadolint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: brew install hadolint
      - run: hadolint ruby-node/{2.6,2.7}/**/*Dockerfile --ignore DL3008 --ignore DL3018
